fun main(){
    print("Student Enrollment No.: ")
    var enro=readLine()!!.toInt()
    print("Student Name: ")
    var name=readLine().toString()
    print("Student Age: ")
    var age=readln().toInt()
    print("Student Branch: ")
    var branch=readLine().toString()
    print("Student Class: ")
    var c=readLine().toString()
    print("Student Batch: ")
    var batch=readLine().toString()
    print("Student College Name: ")
    var clg=readLine().toString()
    print("Student University Name: ")
    var uni=readLine().toString()
    println()
    println("**********************")
    println()
    println("Student's Data: ")
    println("Enrollment No.: $enro")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $c")
    println("Batch: $batch")
    println("College Name: $clg")
    println("University Name: $uni")
}